scheme: Muse

menu:
  home: / || fa fa-home
  about: /about/ || fa fa-user
  Internship: /internship/ || fa fa-briefcase
  blog: /blog/ || fa fa-book
  categories: /categories/ || fa fa-folder
  archives: /archives/ || fa fa-archive

sidebar:
  position: left
  display: post

avatar:
  url: /images/avatar.jpg
  rounded: true

social:
  GitHub: https://github.com/ZionPeng112 || fab fa-github
  Email: mailto:pengqz112@gmail.com || fa fa-envelope

busuanzi_count:
  enable: true
  total_visitors: true
  total_views: true

custom_file_path:
  head: source/_data/custom_head.swig
  bodyEnd: source/_data/custom_body_end.swig
