scheme: Muse

menu:
  Home: /
  About: /about/
  Internship: /internship/
  Blog: /blog/
  Categories: /categories/

sidebar:
  position: left
  display: post

avatar:
  url: /images/avatar.jpg
  rounded: true

social:
  GitHub: https://github.com/ZionPeng112 || fab fa-github
  Email: mailto:pengqz112@gmail.com || fa fa-envelope

busuanzi_count:
  enable: true
  total_visitors: true
  total_views: true

custom_file_path:
  head: source/_data/custom_head.swig
  bodyEnd: source/_data/custom_body_end.swig

# Math Equations Render Support
math:
  every_page: false
  mathjax:
    enable: true
    tags: none  # or 'ams' or 'all'
  katex:
    enable: false

# Mermaid Diagrams Support
mermaid:
  enable: true
  theme:
    light: default
    dark: dark
